services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - watchlist-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - watchlist-network

networks:
  watchlist-network:
    driver: bridge
